language: php

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php -v
    - composer -V
    - vendor/bin/phpunit --version
    - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
