language: php
php:
    - 7.3
cache:
    directories:
        - $HOME/.composer/cache
install: composer install
script:
    - php -v
    - composer -V
    - vendor/bin/phpunit --version
    - vendor/bin/phpunit --verbose --colors=always --coverage-clover coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
